# SPDX-FileCopyrightText: 2025 SAP SE
#
# SPDX-License-Identifier: Apache-2.0

[default.extend-words]
DELET = "DELET" # wrongly detected
fo = "fo" # part of regex fo+

[files]
extend-exclude = [
  "go.mod",
  "vendor/",
  "internal/tasks/fixtures/trivy/*.json",
  "internal/test/setup_consts.go"
]
